### ISSUE TITLE
What is the purpose of a Machine's ssh_name

### ISSUE THREAD

**Issue by rleonid** [hammerlab/biokepi#187]
I can't figure out where it is used. Are we setting this field for nothing or is there a purpose?

**Comment by rleonid** [comment]
I can't quiet figure out what the `name` field is for either.  But there are obviously, many more instances of that variable making it harder to track down.

**Comment by smondet** [comment]
There used to be code to move files around that would build commands like:

```ocaml
let prog =
   Program.shf "scp %s:/foo  %s:/bar"  machineA.ssh_name machineB.ssh_name
```

(or with `rsync` and such I don't remember exactly)
but it was not really portable, so none of those made it to Biokepi while open-sourcing.
The `ssh_name` should maybe go away.


The `name` is for printfs and building "display names" for workflow-nodes (especially in user code since that's where one can use more than one `Machine.t` at once, like `"move dataset from A to B"` etc.).

**Comment by rleonid** [comment]
I'd like to remove `ssh_name` with #197.

I still don't understand why we need `name` for a `Machine.t`. In the scenario were a user creates a workflow that moves data, the user still has the option to call that workflow whatever they choose. Furthermore, that record already has a `host : Host.t` which makes it confusing. I would also recommend removing it.
